# Generated by Django 5.2.11 on 2026-02-21 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaveentry',
            index=models.Index(fields=['user', 'date'], name='leave_entri_user_id_41bcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveentry',
            index=models.Index(fields=['user', 'leave_type'], name='leave_entri_user_id_c91e66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaveentry',
            unique_together={('user', 'date')},
        ),
    ]
